
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int Nombre = 39;
  public static final int Lista_Entrada = 26;
  public static final int Link = 30;
  public static final int Parentesis_Cierre = 22;
  public static final int Apertura_Cuerpo = 6;
  public static final int Parrafo = 36;
  public static final int Fin_Cuerpo = 7;
  public static final int Separador = 38;
  public static final int Dos_Puntos = 34;
  public static final int Email = 10;
  public static final int Variable = 37;
  public static final int Titulo = 8;
  public static final int Multiplicar = 23;
  public static final int Punto = 24;
  public static final int Cadena = 9;
  public static final int Apertura_Tabla = 14;
  public static final int Diagonal = 31;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Parentesis_Apertura = 21;
  public static final int Imprimir = 28;
  public static final int Cierre_Documento = 3;
  public static final int Cierre_Encabezado = 5;
  public static final int Apertura_Imagen = 18;
  public static final int ERROR = 40;
  public static final int Cierre_Imagen = 19;
  public static final int Negrilla = 35;
  public static final int Lista_Fin = 27;
  public static final int Fin_Fila = 20;
  public static final int Resta = 13;
  public static final int Apertura_Documento = 2;
  public static final int Apertura_Encabezado = 4;
  public static final int Punto_y_Coma = 29;
  public static final int Cierre_Tabla = 17;
  public static final int Apertura_Fila = 15;
  public static final int Numero = 25;
  public static final int Suma = 12;
  public static final int Igual = 11;
  public static final int Apertura_Columna = 16;
  public static final int Formato_Imagen = 32;
  public static final int Comillas = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Apertura_Documento",
  "Cierre_Documento",
  "Apertura_Encabezado",
  "Cierre_Encabezado",
  "Apertura_Cuerpo",
  "Fin_Cuerpo",
  "Titulo",
  "Cadena",
  "Email",
  "Igual",
  "Suma",
  "Resta",
  "Apertura_Tabla",
  "Apertura_Fila",
  "Apertura_Columna",
  "Cierre_Tabla",
  "Apertura_Imagen",
  "Cierre_Imagen",
  "Fin_Fila",
  "Parentesis_Apertura",
  "Parentesis_Cierre",
  "Multiplicar",
  "Punto",
  "Numero",
  "Lista_Entrada",
  "Lista_Fin",
  "Imprimir",
  "Punto_y_Coma",
  "Link",
  "Diagonal",
  "Formato_Imagen",
  "Comillas",
  "Dos_Puntos",
  "Negrilla",
  "Parrafo",
  "Variable",
  "Separador",
  "Nombre",
  "ERROR"
  };
}

